# This Json Builds the Risk analysis form the id field for the dropdown hazards is used to grab the relevant existing control and further actions
# To add more dropdowns or existing controls in the future just add the dropdown hazard id with the prefix (_control) or (_further_action)
# Tooltips have been added to the existing control and further action which are exactly the same for the time being, but can be changed whenever if you change the "tooltip" section

riskAnalysisTemplate = [
{
  "title": "Risk Analysis Form",
  "header": "Risks and hazards related to the project",
  "form": {
    "sections": [
      {
        "header": "Hazards Identified",
        "fields": [
          {"id": "compliance", "name": "Compliance", "value":"","required": True},
          {"id": "competence", "name": "Competence", "value":"","required": True},
          {"id": "permission", "name": "Permission", "value":"","required": True},
          {"id": "weather", "name": "Weather","value":"","required": True},
          {"id": "pedestrians_traffic", "name": "Pedestrians and Traffic","value":"","required": True},
          {"id": "emergency", "name": "Emergency","value":"","required": True},
          {"id": "wildlife_pets", "name": "Wildlife, Livestock, Domestic pets etc","value":"","required": True},
          {"id": "collision_nearmiss", "name": "UAS collision or near miss with other air users","value":"","required": True},
          {"id": "maintenance_servicing", "name": "Maintenance and servicing","value":"","required": True},
          {"id": "crash_building", "name": "Crash into building/people","value":"","required": True},
          {"id": "security", "name": "Security","value":"","required": True},
          {"id": "insurance", "name": "Insurance","value":"","required": True},
          {"id": "data_protection", "name": "Data Protection/camera","value":"","required": True},
          {"id": "ground_hazards", "name": "Ground Hazards","value":"","required": True},
          {"id": "other_hazards", "name": "Any other Hazards/risks","value":"","required": True},
        ]
      },
      {
        "header": "Existing Control",
        "fields":[
          {"id": "compliance_control", "name": 
            """All drones/UAVs registered.\n The remote pilot must not fly the aircraft in any of the circumstances described below except in accordance with a permission issued by the CAA.\n Dont fly near airports or airfields without permission from air traffic control, Observe your drone/UAV at all times  stay 150ft (50m) away from people and property.\n Drones/UAVs with surveillance cameras must not be flown within 50 metres of any person unless approval has been permitted, Comply with Operation Manual.""", "tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "competence_control", "name":
            """All drone remote pilots need to be registered with the CAA and all drones/UAVs need to have the registration number attached.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "permission_control", "name":
            """The pilot will seek permission in advance in line with the University procedure.\n Off campus, permission to fly is required from the property owner.\n Where required notification to air traffic control.\n Approval of location and risk assessment to area must be completed.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "weather_control", "name":
            """Accurate weather forecast checked prior to flight.\n Weather to be monitored at all times during flight with a view to landing should weather deteriorate.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "pedestrians_traffic_control", "name":
            """Tape off exclusion zone where possible.\n At least one spotter is dedicated to supervising access to zone.\n Flying in the middle of the field and away from pedestrians and traffic.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "emergency_control", "name":
            """Local emergency arrangements in place.\n Campus induction leaflet communicated.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "wildlife_pets_control", "name":
            """Risk assess area prior to flight of risks to livestock or restrictions.\n Keep a responsible distance away from domestic animals, pets and working animals (e.g. assistance dogs).""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "collision_nearmiss_control", "name":
            """Activity in line with CAA legislative requirements and Operations Manual.\n Air Traffic Control will be informed. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "maintenance_servicing_control", "name":
            """The drone/UAV will be serviced and maintained in line with the manufacturers instructions.\n Batteries will be stored within a fireproof bag whilst they are charging. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "crash_building_control", "name":
            """The remote pilot has undertaken relevant training.\n The Pilot must ensure they are 50 meters away from people and property.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "security_control", "name":
            """No lone working when flying drone/UAV permitted.\n Staff will not leave any property unattended.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "insurance_control", "name":
            """The Universitys public liability and employers liability insurances would respond where damage and/or injury to 3rd party property, assets or individuals was caused by flight of a drone/UAV and the University was found to be negligent.\n Insurance stipulates NQE training required.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "data_protection_control", "name":
            """Consideration must be given in relation to images gathered.\n This must be taken into account when considering the flight location and should be stated in the site-specific risk assessment if applicable.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "ground_hazards_control", "name":
            """e.g. Trees, unstable terrain, buildings, water, etc.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "other_hazards_control", "name":
            """Anything not listed.""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
        ]
      },
      {
        "header": "People at Risk",
        "fields":[
            {"id": "all", "name": "All in vicinity","value":"","required": True},
            {"id": "staff", "name": "Staff in vicinity","value":"","required": True},
            {"id": "students", "name": "Students in vicinity","value":"","required": True},
            {"id": "visitors", "name": "Visitors in vicinity","value":"","required": True},
            {"id": "pedestrians", "name": "Pedestrians","value":"","required": True},
        ]
      },
      {
        "header": "Risk",
         "fields":[
            {"id": "riskScore","name":"riskScore","value":0,"required": True}
        ]
      },
      {
        "header": "Further Actions",
        "fields":[
           {"id": "compliance_further_action", "name":
            """Follow all additional rules when applicable to the specific site.\n Never fly while taking medication, prescribed or otherwise that may impair the pilot.\n Comply with drone code. \n The European Aviation Safety Agency have a drone safety video: www.youtube.com/watch?v=5Xs_eVx4nuw""", "tooltip": "This section of the form is autogenerated based on hazard selected."},
           
          {"id": "competence_further_action", "name":
           """All remote pilots must have evidence of their competence: Current CAA permission, and examples of other clients they have worked for. """, "tooltip": "This section of the form is autogenerated based on hazard selected."},
            
          {"id": "permission_further_action", "name":
           """Planning, administration and operating checklist to be completed.\n Equipment tested carefully before the flight.\n Remote pilot to have NQE approved training.\n Emergency procedures in place.\n Record and report incident in line with CAP382. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "weather_further_action", "name":
           """Poor visibility or weather condition, no flights permitted. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "pedestrians_traffic_further_action", "name":
           """ P&F/H&S informed.\n Wearing of appropriate Hi-Viz jackets. """, "tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "emergency_further_action", "name":
           """Where off-campus consider emergency arrangements.\n P&F/H&S informed.\n Safely land UAS and record/report incidents. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "wildlife_pets_further_action", "name":
           """ Appropriate permissions should be sought from the relevant bodies e.g. Scottish Natural Heritage, National Trust for Scotland, landowners, leaseholders etc. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "collision_nearmiss_further_action", "name":
           """Follow drone code.\n The full regulations can be found at: https://www.caa.co.uk/home/""", "tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "maintenance_servicing_further_action", "name":
           """The batteries will be monitored whilst charging so that they are not overcharged. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "crash_building_further_action", "name":
           """Restriction area set up.\n Consideration where communication is required.\n If the computers link to the quadcopter is lost the hand controller always has the ability to take control and land the drone/UAV. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "security_further_action", "name":
           """Emergency contact number recorded. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "insurance_further_action", "name":
           """Copy of insurance for Drone/UAV use available on request from Finance.\n The building and contents insurance would respond to damage to University owned building and property. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "data_protection_further_action", "name":
           """Respect peoples privacy at all times.\n Send out communication notification when applicable. ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "ground_hazards_further_action", "name":
           """If Any further action needs to be taken ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
          
          {"id": "other_hazards_further_action", "name":
           """If any further action needs to be taken ""","tooltip": "This section of the form is autogenerated based on hazard selected."},
        ]
        
      },
      {
        "header": "Residual Risk",
         "fields":[
            {"id": "residualRiskScore","name":"residualRiskScore","value":0,"required": True}
        ]
        
      },
      {
        "header": "Action Taken By",
           "fields":[
            {"id": "pilot", "name": "pilot","value":"","required": True}
        ]
      },
      {
        "header": "Action Taken When",
          "fields":[
            {"id": "date", "name": "date","value":"","required": True}
        ]
      },
      {
        "header": "Completed",
        "fields":[
          {"id": "check", "name": "check", "value": "", "required": False}
        ]
      }
    ]
  }
}
]
